name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache Cargo dependencies
      uses: actions/cache@v3.2.6
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-rust-
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
